version: '3.8'

services:
  account-manager:
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgres://postgres:123%40Hadi@db:5432/account_manager?sslmode=disable
    depends_on:
      - db

  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123@Hadi
      POSTGRES_DB: account_manager
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
